// ---------------------------------------------------------------------------
// AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
//
// Generated by scripts/generate-legal-content.js from the markdown
// files in /legal. Re-run `node scripts/generate-legal-content.js`
// after editing any legal document.
// ---------------------------------------------------------------------------

export const LEGAL_CONTENT = {
  terms: `# Conditions d'utilisation de Pulse

> **En résumé** — Pulse est un réseau social pour les personnes qui aiment le sport. En créant un compte, vous acceptez ces conditions : vous devez avoir au moins 16 ans, respecter les autres utilisateurs et nos règles de communauté, et vous restez responsable de ce que vous publiez. Nous pouvons suspendre ou supprimer un compte qui enfreint ces règles. Vous pouvez supprimer votre compte à tout moment.

**Application :** Pulse
**Éditeur :** Maximilien MONTANT
**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0

---

## Table des matières

1. [Objet](#1-objet)
2. [Qui peut utiliser Pulse](#2-qui-peut-utiliser-pulse)
3. [Votre compte](#3-votre-compte)
4. [Description du service](#4-description-du-service)
5. [Règles d'utilisation](#5-règles-dutilisation)
6. [Contenu publié par les utilisateurs](#6-contenu-publié-par-les-utilisateurs)
7. [Propriété intellectuelle de Pulse](#7-propriété-intellectuelle-de-pulse)
8. [Disponibilité et évolution du service](#8-disponibilité-et-évolution-du-service)
9. [Responsabilité](#9-responsabilité)
10. [Résiliation et suspension](#10-résiliation-et-suspension)
11. [Droit applicable et litiges](#11-droit-applicable-et-litiges)
12. [Modification de ces conditions](#12-modification-de-ces-conditions)
13. [Contact](#13-contact)

---

## 1. Objet

Les présentes conditions d'utilisation (les « Conditions ») régissent l'accès et l'utilisation de l'application Pulse (le « Service »), éditée par Maximilien MONTANT (l'« Éditeur », « nous »).

En créant un compte ou en utilisant Pulse, vous (l'« Utilisateur », « vous ») acceptez ces Conditions dans leur intégralité. Si vous n'êtes pas d'accord, vous ne devez pas utiliser le Service.

Ces Conditions doivent être lues avec :
- notre **Politique de confidentialité** ;
- notre **Politique de contenu et de modération**.

## 2. Qui peut utiliser Pulse

Pour créer un compte sur Pulse, vous devez :
- avoir au moins **16 ans**. Cet âge correspond au seuil retenu par le Luxembourg pour le consentement numérique des mineurs (article 8 du RGPD) ; en dessous de cet âge, une autorisation parentale serait nécessaire, ce que Pulse ne peut pas vérifier à ce stade ;
- avoir la capacité juridique de conclure un contrat, ou disposer de l'accord de votre représentant légal si la loi qui vous est applicable l'exige ;
- fournir des informations exactes lors de votre inscription.

Si nous découvrons qu'un compte a été créé par une personne ne remplissant pas ces conditions, nous pouvons le suspendre ou le supprimer.

## 3. Votre compte

### 3.1 Création de compte

La création d'un compte nécessite une authentification et la fourniture de certaines informations (voir notre Politique de confidentialité). Vous êtes responsable de la confidentialité de vos identifiants et de toute activité effectuée depuis votre compte.

### 3.2 Types de comptes

Pulse propose plusieurs types de comptes :

| Type de compte | Description |
|---|---|
| Profil privé | Contenu visible uniquement par les personnes que vous acceptez |
| Profil public | Contenu visible par l'ensemble des utilisateurs de Pulse |
| Profil public créateur de contenu | Profil public avec des fonctionnalités supplémentaires liées à la publication de contenu |
| Modérateur / administrateur | Compte disposant de droits de gestion et de modération, encadré par notre Politique de contenu et de modération |

### 3.3 Exactitude des informations

Vous vous engagez à tenir vos informations de profil à jour et à ne pas usurper l'identité d'un tiers.

## 4. Description du service

Pulse est une application sociale dédiée au sport, qui vous permet notamment de :
- publier des posts, les liker et les commenter ;
- échanger par messagerie privée et en conversations de groupe (à venir) ;
- ajouter ou retirer des amis, envoyer des demandes de suivi et vous abonner à d'autres profils ;
- créer ou rejoindre des événements et des clubs, et demander à y participer ;
- gérer un profil privé ou public.

Le Service est actuellement proposé **gratuitement**. Des fonctionnalités payantes seront introduites ultérieurement.

## 5. Règles d'utilisation

En utilisant Pulse, vous vous engagez à respecter la loi applicable ainsi que notre **Politique de contenu et de modération**, qui détaille les comportements interdits (harcèlement, contenu illégal, usurpation d'identité, spam, triche, etc.) et les sanctions possibles.

## 6. Contenu publié par les utilisateurs

### 6.1 Votre contenu reste à vous

Vous conservez tous vos droits de propriété intellectuelle sur les contenus que vous publiez sur Pulse (textes, photos, vidéos, etc.), désignés ci-après « Contenu Utilisateur ».

### 6.2 Licence que vous nous accordez

En publiant du Contenu Utilisateur, vous nous accordez une licence non exclusive, gratuite et valable dans le monde entier, pour héberger, stocker, reproduire, afficher, diffuser et modérer ce contenu, dans la seule mesure nécessaire au fonctionnement du Service (par exemple pour l'afficher dans le fil d'actualité des personnes concernées). Cette licence prend fin lorsque vous supprimez le contenu concerné ou votre compte, sous réserve des copies conservées temporairement pour des raisons techniques ou légales (voir notre Politique de confidentialité).

### 6.3 Votre responsabilité

Vous êtes seul responsable du Contenu Utilisateur que vous publiez, et vous garantissez qu'il ne viole pas les droits d'un tiers ni la loi applicable.

## 7. Propriété intellectuelle de Pulse

Le nom « Pulse », le logo, le design, le code source, les interfaces et l'ensemble des contenus édités par nous (hors Contenu Utilisateur) sont notre propriété ou font l'objet d'une licence en notre faveur. Ils sont protégés par le droit de la propriété intellectuelle.

Vous ne pouvez pas copier, reproduire, décompiler ou exploiter le Service ou ses éléments en dehors de l'usage normal autorisé par ces Conditions, ni porter atteinte aux droits de tiers en utilisant Pulse.

## 8. Disponibilité et évolution du service

Pulse est un produit en développement continu (MVP). Nous pouvons ajouter, modifier ou retirer des fonctionnalités à tout moment, et nous ne garantissons pas une disponibilité continue ou exempte d'erreurs du Service.

## 9. Responsabilité

Dans la mesure permise par la loi applicable :
- le Service est fourni **« en l'état »** et **« selon disponibilité »**, sans garantie de fonctionnement ininterrompu ou exempt d'erreurs ;
- nous ne sommes pas responsables des usages abusifs du Service par d'autres utilisateurs (propos, comportements, contenus publiés) ;
- nous ne garantissons pas l'exactitude, la fiabilité ou la véracité des contenus publiés par les utilisateurs ;
- notre responsabilité, lorsqu'elle peut être engagée, est limitée aux dommages directs et prévisibles ; nous excluons les dommages indirects (perte de données, de profits, préjudice moral, etc.), sauf faute intentionnelle ou lourde de notre part, ou lorsque la loi applicable ne permet pas une telle limitation (par exemple à l'égard des consommateurs).

Rien dans ces Conditions ne limite une responsabilité qui ne peut légalement être exclue ou limitée.

## 10. Résiliation et suspension

### 10.1 Résiliation par vous

Vous pouvez supprimer votre compte à tout moment depuis l'application. La suppression entraîne les conséquences décrites dans notre Politique de confidentialité.

### 10.2 Suspension ou résiliation par nous

Nous pouvons suspendre ou supprimer votre compte en cas de violation de ces Conditions ou de notre Politique de contenu et de modération, selon les modalités décrites dans cette dernière (notamment en cas de comportement inadéquat répété, ou de comportement dangereux ou illégal). Nous pouvons agir immédiatement et arbitrairement en cas d'atteinte à la sécurité ou de violation grave. Il n'est pas possible de faire appel une fois son compte supprimé ou suspendu.

### 10.3 Effets de la résiliation

Certains effets sont immédiats : perte d'accès au Service, retrait du contenu visible par les autres utilisateurs. Certaines obligations survivent à la fermeture du compte, notamment celles liées à la sécurité, à la gestion d'un litige en cours et à la conservation légale de certaines données (voir notre Politique de confidentialité).

## 11. Droit applicable et litiges

Ces Conditions sont régies par le droit luxembourgeois. Si vous êtes un consommateur résidant dans l'Union européenne, les dispositions impératives de protection des consommateurs de votre pays de résidence continuent de s'appliquer en votre faveur, indépendamment de ce choix de droit.

Tout litige sera soumis, à défaut de résolution amiable, aux tribunaux compétents du Luxembourg, sans préjudice de votre droit, en tant que consommateur, de saisir les tribunaux de votre pays de résidence.

## 12. Modification de ces conditions

Nous pouvons modifier ces Conditions, notamment pour refléter une évolution du Service ou de la loi applicable. En cas de modification substantielle, nous vous en informerons par un moyen raisonnable (notification dans l'application ou par e-mail). La poursuite de l'utilisation de Pulse après une modification vaut acceptation des nouvelles Conditions.

## 13. Contact

Pour toute question relative à ces Conditions :

**E-mail :** maximilien.montant@gmail.com

---

**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0
`,
  privacy: `# Politique de confidentialité de Pulse

> **En résumé** — Pulse collecte les informations que vous fournissez à l'inscription (nom, e-mail, âge, sports pratiqués, etc.) pour faire fonctionner l'application et personnaliser votre expérience. Nous ne vendons pas vos données. Nous utilisons Supabase pour héberger l'application et PostHog pour comprendre comment elle est utilisée. Vous pouvez à tout moment demander l'accès, la correction, l'export ou la suppression de vos données.

**Application :** Pulse
**Responsable du traitement :** Maximilien MONTANT
**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0

---

## Table des matières

1. [Qui est responsable de vos données](#1-qui-est-responsable-de-vos-données)
2. [Quelles données nous collectons](#2-quelles-données-nous-collectons)
3. [Pourquoi nous collectons ces données](#3-pourquoi-nous-collectons-ces-données)
4. [Base légale du traitement](#4-base-légale-du-traitement)
5. [Qui a accès à vos données](#5-qui-a-accès-à-vos-données)
6. [Transferts de données hors Union européenne](#6-transferts-de-données-hors-union-européenne)
7. [Durée de conservation](#7-durée-de-conservation)
8. [Vos droits](#8-vos-droits)
9. [Sécurité de vos données](#9-sécurité-de-vos-données)
10. [Mineurs](#10-mineurs)
11. [Cookies et traceurs](#11-cookies-et-traceurs)
12. [Modifications de cette politique](#12-modifications-de-cette-politique)
13. [Contact et réclamations](#13-contact-et-réclamations)

---

## 1. Qui est responsable de vos données

Le responsable du traitement de vos données personnelles est :

**Maximilien MONTANT**, éditeur de l'application Pulse
Luxembourg — 1651
Contact : maximilien.montant@gmail.com

Pulse est développé par un développeur indépendant. Aucun délégué à la protection des données (DPO) n'est désigné à ce stade ; toute question relative à vos données peut être adressée directement à l'e-mail ci-dessus.

## 2. Quelles données nous collectons

Nous collectons les données que vous nous fournissez lors de votre inscription. Les données obligatoires à fournir pour permettre la création de votre compte sont les suivantes :

| Donnée | Finalité principale |
|---|---|
| Langue | Personnalisation de l'UI et options de langues à venir |
| Nom et prénom | Identification, présentation de votre profil |
| Adresse e-mail | Création et sécurité du compte, communications liées au Service |
| Date de naissance | Vérification de l'âge minimum requis |
| Pays | Personnalisation (ex. suggestions d'événements ou de clubs proches) et respect de la juridiction adaptée |
| Sports pratiqués | Personnalisation du contenu et présentation de votre profil |
| Niveau de pratique | Personnalisation du contenu pour des évènements, clubs et posts adapté à votre niveau sportif |
| Type de pratique | Distingue les utilisateurs récréationnels et compétitifs pour permettre une meilleure personnalisation des évènements, clubs et posts proposés |
| Disponibilité | Personnalisation de votre expérience, présentation d'évènements et clubs adaptés à votre disponibilité |
| Localisation | Fonctionnalités géolocalisées, **uniquement si vous l'autorisez** |

D'autres données à caractère facultatif peuvent être partagées avec nous, elles permettront une meilleure personnalisation de votre expérience.

En plus de ces informations, nous traitons automatiquement :
- **le contenu que vous créez** : posts, commentaires, messages, événements, clubs ;
- **vos interactions** : likes, abonnements, demandes de suivi, participations à des événements ou clubs, signalements, blocages ;
- **des données techniques minimales** nécessaires au fonctionnement et à la sécurité de l'application (ex. journaux techniques).

## 3. Pourquoi nous collectons ces données

Nous utilisons vos données pour :
- créer et faire fonctionner votre compte et votre profil ;
- personnaliser votre expérience (contenu, mise en relation selon vos sports et votre activité) ;
- vous permettre de vous présenter aux autres utilisateurs sur l'application ;
- assurer la sécurité du Service et la modération des contenus ;
- comprendre l'utilisation de l'application afin de l'améliorer (via PostHog) ;
- respecter nos obligations légales (par exemple, vérifier l'âge minimum).

## 4. Base légale du traitement

- **Exécution du contrat** : compte, profil, fonctionnalités sociales que vous avez demandées.
- **Intérêt légitime** : sécurité, prévention de la fraude, amélioration du Service, mesure d'audience de base.
- **Consentement** : localisation précise, que vous pouvez retirer à tout moment dans les réglages de votre appareil ou de l'application.
- **Obligation légale** : lorsque la loi nous impose de conserver ou de communiquer certaines données.

## 5. Qui a accès à vos données

Nous ne vendons pas vos données. Elles peuvent être transmises aux prestataires techniques suivants, qui agissent comme sous-traitants et n'utilisent vos données que pour nous fournir leur service :

| Prestataire | Rôle | Données concernées |
|---|---|---|
| **Supabase** | Hébergement, base de données, authentification, stockage des contenus, outils de modération | Données de compte, contenus publiés, messages, informations techniques |
| **PostHog** | Mesure d'audience et analyse d'usage | Données d'usage de l'application (actions, écrans consultés, événements techniques) — pas le contenu de vos messages privés |

Certains outils utilisés pour développer l'application (par exemple un assistant de codage utilisé par le développeur, ou des bibliothèques techniques qui s'exécutent uniquement sur votre appareil) n'ont pas accès à vos données de production et ne sont pas des destinataires de vos données personnelles.

Vos données peuvent aussi être communiquées à des autorités publiques si la loi l'exige.

## 6. Transferts de données hors Union européenne

Si Supabase et/ou PostHog traitent ou stockent des données en dehors de l'Espace économique européen, ce transfert est encadré par les garanties prévues par le RGPD, notamment les clauses contractuelles types de la Commission européenne. L'hébergement des données de Supabase et de PostHog est effectué respectivement en France et en Europe.

## 7. Durée de conservation

- Les données de votre compte sont conservées **tant que votre compte est actif**.
- Lorsque vous supprimez votre compte, vos données personnelles sont supprimées ou anonymisées dans un délai de **30 jours**.
- Certaines données peuvent être conservées plus longtemps lorsque cela est nécessaire pour des raisons de sécurité, pour la gestion d'un litige en cours, ou pour respecter une obligation légale de conservation.
- Vous pouvez demander l'export de vos données dans un format lisible (par exemple JSON ou CSV) en nous contactant à l'adresse ci-dessous.

## 8. Vos droits

Conformément au RGPD, vous disposez des droits suivants :
- **droit d'accès** : obtenir une copie des données que nous détenons sur vous ;
- **droit de rectification** : corriger des données inexactes ou incomplètes ;
- **droit à l'effacement** : demander la suppression de vos données, dans les limites prévues par la loi ;
- **droit à la limitation du traitement** ;
- **droit d'opposition**, notamment pour les traitements fondés sur notre intérêt légitime ;
- **droit à la portabilité** de vos données ;
- **droit de retirer votre consentement** à tout moment (ex. localisation), sans remettre en cause la licéité des traitements déjà effectués.

Pour exercer ces droits, contactez-nous à **maximilien.montant@gmail.com**. Nous répondons dans un délai maximum d'un mois, pouvant être porté à trois mois pour les demandes complexes (vous en seriez informé).

Vous pouvez aussi introduire une réclamation auprès de l'autorité de contrôle luxembourgeoise :

**Commission nationale pour la protection des données (CNPD)**
15, Boulevard du Jazz, L-4370 Belvaux, Luxembourg
Site : cnpd.public.lu

## 9. Sécurité de vos données

Nous mettons en œuvre des mesures techniques et organisationnelles raisonnables pour protéger vos données (notamment via les fonctionnalités de sécurité fournies par Supabase). Aucun système n'étant totalement infaillible, nous ne pouvons garantir une sécurité absolue.

## 10. Mineurs

Pulse n'est pas destiné aux personnes de moins de 16 ans. Si nous apprenons qu'un compte a été créé par une personne de moins de 16 ans, nous le supprimons.

## 11. Cookies et traceurs

Selon la version utilisée (application mobile ou site web), Pulse peut utiliser des identifiants techniques et des outils de mesure d'audience (PostHog) pour comprendre l'usage de l'application. Sur la version web, si des cookies ou traceurs non essentiels sont utilisés, votre consentement vous sera demandé conformément à la réglementation applicable, et vous pourrez le refuser sans perdre l'accès aux fonctionnalités essentielles.
## 12. Modifications de cette politique

Nous pouvons modifier cette politique, notamment en cas d'évolution du Service, des prestataires utilisés, ou de la loi applicable. Les modifications substantielles vous seront signalées dans l'application ou par e-mail.

## 13. Contact et réclamations

**E-mail :** maximilien.montant@gmail.com

---

**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0
`,
  bugReport: `# Signaler un bug ou un problème technique

> **En résumé** — Cette page explique comment signaler un problème technique (bug) sur Pulse : où cliquer, quelles informations donner, et sous quel délai nous traitons votre signalement. Pour signaler un contenu ou un utilisateur, ou pour toute autre demande, utilisez les procédures dédiées mentionnées ci-dessous.

**Application :** Pulse
**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0

---

## 1. Que signaler ici

Utilisez cette procédure uniquement pour un **problème technique** : plantage de l'application, fonctionnalité qui ne fonctionne pas, écran bloqué, erreur d'affichage, etc.

Ne signalez pas ici :
- un contenu ou un profil qui enfreint nos règles → utilisez le bouton **Signaler**, disponible depuis le menu d'options d'un post ou d'un profil (voir notre **Politique de contenu et de modération**) ;
- une question, une suggestion ou une demande générale → contactez le **Support** (voir nos coordonnées ci-dessous).

## 2. Comment signaler un bug

Depuis l'application :

1. Ouvrir les **paramètres** de l'application ;
2. Appuyer sur **Signaler un bug** dans la section Support ;
3. Décrire le problème rencontré ;
4. Consulter les informations qui seront collectées automatiquement (appareil, système, version, etc.) ;
5. Appuyer sur **Envoyer**.

Vous pouvez aussi nous écrire directement à **maximilien.montant@gmail.com** en indiquant « Bug » dans l'objet du message.

## 3. Informations à fournir

Pour que nous puissions comprendre et corriger le problème rapidement, merci d'indiquer autant que possible :
- une description claire du problème ;
- les étapes pour reproduire le problème ;
- une capture d'écran ou une vidéo, si possible (par mail);
- le modèle de votre appareil et la version de l'application (visible dans les paramètres) ;
- le moment approximatif où le problème est survenu.

## 4. Délai de traitement

Nous traitons les signalements de bugs dans un délai allant de **quelques jours à quelques semaines**, selon leur nature et leur gravité. Les problèmes liés à la sécurité sont traités en priorité.

## 5. Ce qui n'est pas couvert ici

- Les signalements de contenu ou de comptes → voir notre **Politique de contenu et de modération**.
- Les demandes générales (suggestions, questions) → voir le Support ci-dessous.

## 6. Contact

**E-mail :** maximilien.montant@gmail.com

---

**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0
`,
  moderation: `# Politique de contenu et de modération de Pulse

> **En résumé** — Pulse est fait pour encourager et partager la pratique du sport, pas pour nuire aux autres. Cette politique explique ce qui est autorisé, ce qui est interdit, comment signaler un problème, et quelles sanctions peuvent s'appliquer.

**Application :** Pulse
**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0

---

## Table des matières

1. [Objectif de cette politique](#1-objectif-de-cette-politique)
2. [Ce que nous encourageons sur Pulse](#2-ce-que-nous-encourageons-sur-pulse)
3. [Comportements et contenus interdits](#3-comportements-et-contenus-interdits)
4. [Comptes modérateurs et administrateurs](#4-comptes-modérateurs-et-administrateurs)
5. [Signaler un contenu ou un compte](#5-signaler-un-contenu-ou-un-compte)
6. [Sanctions applicables](#6-sanctions-applicables)
7. [Suspension et suppression de compte](#7-suspension-et-suppression-de-compte)
8. [Blocage entre utilisateurs](#8-blocage-entre-utilisateurs)
9. [Mise à jour de cette politique](#9-mise-à-jour-de-cette-politique)
10. [Contact](#10-contact)

---

## 1. Objectif de cette politique

Cette politique s'applique à tous les utilisateurs de Pulse. Elle complète nos **Conditions d'utilisation** et précise les règles de communauté, la procédure de signalement, et les sanctions possibles.

## 2. Ce que nous encourageons sur Pulse

Pulse est fait pour :
- partager vos entraînements, vos résultats et votre progression sportive ;
- encourager et soutenir les autres utilisateurs ;
- organiser et rejoindre des événements ou des clubs sportifs ;
- échanger autour de votre pratique du sport, dans le respect des autres.

## 3. Comportements et contenus interdits

Sont strictement interdits sur Pulse :

| Catégorie | Exemples |
|---|---|
| Harcèlement, insultes, discrimination | Propos dégradants, moqueries répétées, discrimination fondée sur l'origine, le genre, l'orientation, le handicap, etc. |
| Contenu sexuel explicite | Nudité, contenu à caractère pornographique |
| Contenu violent ou dangereux | Incitation à la violence, mise en scène d'actes dangereux |
| Spam, promotion trompeuse, phishing | Messages en masse, fausses promotions, tentatives d'hameçonnage |
| Usurpation d'identité | Se faire passer pour une autre personne ou une entité |
| Partage de données personnelles d'autrui | Publier les coordonnées, l'adresse ou toute donnée privée d'un tiers sans son accord |
| Triche, faux comptes, automatisation abusive | Comptes multiples frauduleux, bots, manipulation artificielle de l'engagement |
| Contenu illégal | Tout contenu contraire à la loi applicable |
| Sport détourné pour inciter à des comportements dangereux | Défis sportifs dangereux, incitation au dopage ou à des pratiques mettant en danger la santé |

Le partage de vos entraînements, résultats, progression et photos sportives est bienvenu, tant que ce contenu ne met pas en danger votre sécurité ou celle des autres.

## 4. Comptes modérateurs et administrateurs

Certains comptes disposent d'un rôle de modérateur ou d'administrateur. Ces comptes peuvent examiner les signalements, retirer du contenu et appliquer des sanctions conformément à cette politique. Ils restent soumis aux mêmes règles de communauté que tout autre utilisateur.

## 5. Signaler un contenu ou un compte

| | |
|---|---|
| **Qui peut signaler** | Tout utilisateur de Pulse |
| **Quoi signaler** | Un post, ou un profil public |
| **Où cliquer** | Menu d'options (⋯) du post ou du profil concerné, puis **Signaler** |
| **Informations à fournir** | Toute information permettant de comprendre et justifier le signalement |
| **Délai de traitement** | De quelques jours à quelques semaines |

**Après le signalement :** notre équipe examine le contenu ou le compte signalé. Selon le résultat, soit aucune suite n'est donnée (signalement non fondé), soit une sanction est appliquée à l'encontre du compte signalé (voir section 6). Nous ne communiquons pas systématiquement à l'auteur du signalement le détail de la décision prise, pour des raisons de confidentialité.

## 6. Sanctions applicables

Selon la gravité et la récurrence du comportement, nous pouvons appliquer :
- une **restriction temporaire** de la possibilité de publier des posts ;
- un **bannissement ou une suppression définitive du compte**, de manière irréversible, en cas de comportement grave ou répété.

## 7. Suspension et suppression de compte

| | |
|---|---|
| **Motifs** | Tout comportement inadéquat répété, ou tout comportement dangereux ou illégal |
| **Caractère** | Définitif |
| **Notification préalable** | Non, nous ne sommes pas tenus de vous avertir avant d'agir |
| **Possibilité d'appel** | Non, cette décision n'est pas soumise à une procédure d'appel interne |
| **Action immédiate** | Oui, possible sans délai en cas de risque pour la sécurité ou de violation grave |

## 8. Blocage entre utilisateurs

Indépendamment de notre procédure de signalement, vous pouvez à tout moment **bloquer** un autre utilisateur pour ne plus voir son contenu et l'empêcher d'interagir avec vous ou de vous contacter.

## 9. Mise à jour de cette politique

Nous pouvons faire évoluer cette politique pour l'adapter à de nouveaux usages ou à l'évolution de la loi. Les modifications substantielles vous seront signalées dans l'application.

## 10. Contact

**E-mail :** maximilien.montant@gmail.com

---

**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0
`,
  imprint: `# Mentions légales et contact — Pulse

> **En résumé** — Cette page présente qui édite l'application Pulse et comment nous contacter.

**Application :** Pulse
**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0

---

## 1. Éditeur de l'application

| | |
|---|---|
| **Nom** | Maximilien MONTANT |
| **Statut** | Personne physique |
| **Pays d'établissement** | Luxembourg |
| **Adresse postale** | 1651 |
| **Numéro d'immatriculation (RCS, TVA, etc., le cas échéant)** | Aucun |
| **E-mail de contact** | maximilien.montant@gmail.com |

L'application Pulse est publiée et développée par Maximilien MONTANT, ci-après « l'Éditeur ».

## 2. Hébergement

| Élément | Prestataire |
|---|---|
| Backend, base de données, authentification, stockage | Supabase |
| Distribution de l'application mobile | Site Web |
| Hébergement du site web, le cas échéant | [à compléter] |

Les coordonnées complètes de ces prestataires sont disponibles sur leurs sites respectifs.

## 3. Propriété intellectuelle

Le nom « Pulse », son logo, son design et son contenu sont protégés par le droit de la propriété intellectuelle. Voir nos **Conditions d'utilisation** pour le détail.

## 4. Protection des données personnelles

Pour toute question relative à vos données personnelles, consultez notre **Politique de confidentialité**, ou contactez-nous à l'adresse ci-dessous. Vous pouvez également contacter l'autorité de contrôle luxembourgeoise :

**Commission nationale pour la protection des données (CNPD)**
15, Boulevard du Jazz, L-4370 Belvaux, Luxembourg
Site : cnpd.public.lu

## 5. Contact

**E-mail :** maximilien.montant@gmail.com

Pour signaler un bug, utilisez la procédure décrite dans **Signaler un bug ou un problème technique**. Pour signaler un contenu ou un compte, utilisez le bouton **Signaler** décrit dans notre **Politique de contenu et de modération**.

---

**Date d'entrée en vigueur :** 15 août 2026
**Dernière mise à jour :** 7 août 2026
**Version du document :** 1.0
`,
} as const;

export type LegalContentKey = keyof typeof LEGAL_CONTENT;
