// ---------------------------------------------------------------------------
// PULSE — Localized data-catalog dictionaries
//
// These dictionaries hold English labels for DATA values that are persisted in
// the database using the French labels from lib/constants.ts (sport names,
// levels, practice types, objectives, public statuses, event categories, …).
// They are NOT app-chrome strings, so they live here instead of translations.ts
// to keep the interface-key set focused and parity-checkable.
//
// `getLabel` in lib/i18n.ts reads the active language: FR mode returns the
// original value unchanged; EN mode maps through EN_LABELS, falling back to the
// original value when a mapping is missing (proper nouns, ratings, etc.).
//
// Adding a new language later means adding another dictionary here and
// extending the lookup in lib/i18n.ts.
// ---------------------------------------------------------------------------

export const EN_LABELS: Record<string, string> = {
  // ── Sports (also covered by translations keys `sports.*`) ─────────────
  Football: "Football",
  Basketball: "Basketball",
  Tennis: "Tennis",
  "Course à pied": "Running",
  Cyclisme: "Cycling",
  Natation: "Swimming",
  Volleyball: "Volleyball",
  Handball: "Handball",
  Padel: "Padel",
  Badminton: "Badminton",
  Fitness: "Fitness",
  Rugby: "Rugby",
  Squash: "Squash",
  "Tennis de table": "Table tennis",
  "Arts martiaux": "Martial arts",
  Yoga: "Yoga",
  Pilates: "Pilates",
  Boxe: "Boxing",
  Escalade: "Climbing",
  Golf: "Golf",
  Danse: "Dance",
  Surf: "Surfing",

  // ── Common / shared tokens ─────────────────────────────────────────────
  Autre: "Other",
  Débutant: "Beginner",
  Intermédiaire: "Intermediate",
  Confirmé: "Advanced",
  Compétition: "Competition",
  Élite: "Elite",
  Loisir: "Leisure",
  Mixte: "Mixed",
  "Entraînement structuré": "Structured training",
  Avancé: "Advanced",
  Club: "Club",
  "Club amateur": "Amateur club",
  "Club loisir": "Leisure club",
  "Club compétition": "Competition club",

  // ── Levels (SPORT_LEVELS) ─────────────────────────────────────────────
  Régional: "Regional",
  National: "National",
  "Semi-pro": "Semi-pro",
  Pro: "Pro",
  "Marche active": "Brisk walking",
  "5 km": "5 km",
  "10 km": "10 km",
  "Semi-marathon": "Half marathon",
  Marathon: "Marathon",
  Ultra: "Ultra",
  Découverte: "Discovery",
  "Gran fondo": "Gran fondo",
  "Compétition UCI amateur": "Amateur UCI competition",
  Apprentissage: "Learning",
  Maître: "Master",
  "Compétition régionale": "Regional competition",
  "Compétition nationale": "National competition",
  "4e série": "4th series",
  "3e série": "3rd series",
  "2e série": "2nd series",
  "1re série": "1st series",
  Nationale: "National",
  "Remise en forme": "Getting fit",
  Hypertrophie: "Hypertrophy",
  Force: "Strength",
  "Cross-training": "Cross-training",
  "Préparation athlétique": "Athletic preparation",
  "École de rugby": "Rugby school",
  "Fédérale 3": "Fédérale 3",
  "Fédérale 2": "Fédérale 2",
  "Fédérale 1": "Fédérale 1",
  "Pro D2": "Pro D2",
  "Top 14": "Top 14",
  Combat: "Fighting",
  Vinyasa: "Vinyasa",
  Yin: "Yin",
  Rééducation: "Rehabilitation",
  Amateur: "Amateur",
  Préparation: "Preparation",

  // ── Practices (SPORT_PRACTICES) ───────────────────────────────────────
  "Foot à 5/7": "5/7-a-side football",
  "Entraînement technique": "Technical training",
  Street: "Street",
  "3x3": "3x3",
  "Shooting / skills": "Shooting / skills",
  Tournois: "Tournaments",
  "Cours collectifs": "Group lessons",
  "Padel en complément": "Padel as a complement",
  "Compétition ITF": "ITF competition",
  Tapis: "Treadmill",
  Route: "Road",
  Trail: "Trail",
  Piste: "Track",
  Fractionné: "Interval training",
  Gravel: "Gravel",
  VTT: "Mountain bike",
  "Home trainer": "Indoor trainer",
  "Bassin loisir": "Recreational pool",
  Maîtres: "Masters",
  "Eau libre": "Open water",
  Technique: "Technique",
  "Prépa triathlon": "Triathlon prep",
  Beach: "Beach",
  "Salle loisir": "Indoor leisure",
  "Salle compétition": "Indoor competition",
  "Mixte entreprise": "Corporate mixed",
  "Compétition jeunes": "Youth competition",
  "Compétition adultes": "Adult competition",
  Ligue: "League",
  Coaching: "Coaching",
  "Coaching perso": "Personal coaching",
  Double: "Doubles",
  Simple: "Singles",
  Musculation: "Strength training",
  Cardio: "Cardio",
  HIIT: "HIIT",
  "Yoga/Pilates": "Yoga/Pilates",
  Touch: "Touch",
  XV: "XV",
  VII: "VII",
  "Self-défense": "Self-defense",
  Studio: "Studio",
  Maison: "Home",
  Falaise: "Cliff",
  Bloc: "Bouldering",
  Salle: "Indoor",
  "Practice": "Practice",
  Spectacle: "Performance",
  Bodyboard: "Bodyboarding",

  // ── Objectives (OBJECTIVES) ───────────────────────────────────────────
  "Perdre du poids": "Lose weight",
  "Prendre du muscle": "Build muscle",
  "Améliorer mon endurance": "Improve my endurance",
  "Reprendre le sport": "Get back into sport",
  "Rencontrer des partenaires": "Meet practice partners",
  "Participer à des compétitions": "Take part in competitions",
  "Réduire le stress": "Reduce stress",
  "Améliorer ma souplesse": "Improve my flexibility",
  "Préparer un objectif (course, triathlon…)": "Prepare for a goal (race, triathlon…)",
  "Découvrir un nouveau sport": "Discover a new sport",

  // ── Public profile statuses (PUBLIC_SPORT_STATUSES) ───────────────────
  Coach: "Coach",
  Récréatif: "Recreational",
  "Semi-Professionnel": "Semi-professional",
  Professionnel: "Professional",

  // ── Event categories (EVENT_CATEGORIES) ───────────────────────────────
  Entraînement: "Training",
  Sortie: "Outing",
  Social: "Social",

  // ── Time-of-day / misc used by date helpers ───────────────────────────
  "Aujourd'hui": "Today",
  Hier: "Yesterday",
  "à l'instant": "just now",
  "il y a": "ago",
};